In [1]:
import torch

In [2]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.9698, 0.9004],
        [0.5741, 0.9226]])
tensor([[0.3037, 0.1658],
        [0.2522, 0.8974]])


In [4]:
z = torch.add(x, y)  # Same as 'z = x + y'
print(z)

tensor([[1.2735, 1.0662],
        [0.8262, 1.8200]])


In [5]:
# or an in-place operation (PS: in-plave operations have a "_" at the end)
y.add_(x)
print(y)

tensor([[1.2735, 1.0662],
        [0.8262, 1.8200]])


In [6]:
a = torch.rand(2, 2)
z = a - x  # or torch.sub(a,x)
print(z)

tensor([[-0.5621, -0.3789],
        [ 0.2914, -0.0699]])


In [9]:
# Other functions:
# torch.mul(a,x) - OR a.mul_(x) for in-place [will modify 'a'] - OR 'a * x'
# torch.div 
# etc.
# EXTRA: 'a @ x' (is equilavent to do the matrix multiplication between 'a' and 'x')
#         Or you can use 'a.matmul(x)' (or torch.matmul(a,x, out=<any_var>))

In [10]:
b = torch.rand(5, 3)
print(b)

tensor([[0.1643, 0.7283, 0.2154],
        [0.6831, 0.8369, 0.5627],
        [0.9321, 0.4373, 0.5476],
        [0.7194, 0.4270, 0.6299],
        [0.0186, 0.2397, 0.7174]])


In [13]:
# Slicing
print(b[:,0]) # all the rows but only column 0
print(b[1,:]) # only row 1 and all the columns

tensor([0.1643, 0.6831, 0.9321, 0.7194, 0.0186])
tensor([0.6831, 0.8369, 0.5627])


In [19]:
# get a value (a tensor) and then convert to a primitive type '.item()'
print(b[0,0].dtype)
bb = b[0,0].item() # PS: this function only works if you have one element
print(bb)
print(type(bb))

torch.float32
0.16427046060562134
<class 'float'>


In [25]:
# Reshaping a tensor
c = b.view(3,5) # one dimension
print(c.size())

torch.Size([3, 5])


In [27]:
# From numpy to a tensor (and vice-versa)
import numpy as np

d = torch.ones(5)
print(d)

tensor([1., 1., 1., 1., 1.])


In [29]:
d_np = d.numpy() #convert to numpy
print(d_np)
print(type(d_np))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [30]:
# IMPORTANT: both objects ('d' and 'd_np') will share the same memory location (if on GPU)
#            Therefore, if you change one, you'll also change the other.

d.add_(1)

tensor([2., 2., 2., 2., 2.])

In [31]:
# Now you should see the same values
print(d)
print(d_np)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [37]:
# From a numpy to tensor

e_np = np.ones(5)
print(a)

e = torch.from_numpy(e_np)
print(e)

tensor([[0.4076, 0.5215],
        [0.8654, 0.8527]])
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [40]:
# PS: This is higher than 2 because I ran this command many times (it keeps adding 1)
e += 1
print(e)
print(e_np) # should always be the same as 'e'

tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
[4. 4. 4. 4. 4.]


In [41]:
# If you have GPU, you can do this
if torch.cuda.is_available():
    device = torch.device("cuda")
    x_gpu = torch.ones(5, device=device)
    # OR (same as above):
    x2_gpu = torch.ones(5).to(device)
    # Now if you do any operation (e.g. the below), it will be done in the GPU
    x_gpu +=1
    # PS: If you try to transform it back into a numpy array (x_gpu.numpy()), that'll error!
    # That is because numpy can only handle CPU tensors
    # To do that conversion to numpy, you have to conver to a CPU tensor first:
    x_gpu = x2_gpu.to("cpu") #Now on CPU

In [42]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    a = a.to("cuda")

In [ ]:
# NOTE ON IN-PLACE OPERATION (from official documentation):
# In-place operations save some memory, but can be problematic when computing derivatives because of
# an immediate loss of history. Hence, their use is discouraged.